#!/bin/bash
clear

cd

cd ..

cd usr/etc

apt install toilet

apt install figlet

pkg install toilet

pkg install figlet

echo "in the text editor about to apear scroll below and paste the copied\n item after filling the form below"

echo enter d name u which to display on ur termux

read user

#echo $user

figlet -f slant -t -c copy the next line

echo clear toilet -F gay  $user

#command= toilet --filter  gay $user

#
eval $command

sleep 10s

echo 'scroll below the writings in the text editor and paste copied code'

sleep 3s

echo after pasting below then tap CTRL and x 

sleep 15s

nano bash.bashrc

clear

toilet -F gay  $user
